version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greensteps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/greensteps?schema=public
      - JWT_SECRET=${JWT_SECRET:-dev-super-secret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM=${SMTP_FROM:-GreenSteps <no-reply@greensteps.app>}
      - UPLOAD_STRATEGY=${UPLOAD_STRATEGY:-local}
      - UPLOAD_DIR=${UPLOAD_DIR:-/app/uploads}
      - CLOUDINARY_URL=${CLOUDINARY_URL:-}
      - PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:5050
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  pgdata:
